# Generated by Django 5.1.4 on 2025-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oson_app', '0003_alter_category_name_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
    ]
