# Generated by Django 5.1.4 on 2025-01-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oson_app', '0004_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
