# Generated by Django 5.1.4 on 2025-01-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oson_app', '0011_alter_productsgallery_image_comment_productsviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='products',
            new_name='product',
        ),
    ]
