# Generated by Django 5.1.4 on 2025-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oson_app', '0013_products_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgallery',
            name='image',
            field=models.ImageField(upload_to='images/products/details', verbose_name='Изображение продукта'),
        ),
    ]
