# Generated by Django 5.1.4 on 2025-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oson_app', '0014_alter_productsgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgallery',
            name='image',
            field=models.ImageField(upload_to='images/products_gallery', verbose_name='Изображение продукта'),
        ),
    ]
